<?php

namespace AppBundle\Repository;

/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getComments($id){
        $qb = $this->createQueryBuilder('comments');

        $qb -> where('comments.articleId = :id')
            ->setParameter('id', $id);

        return $qb
            ->getQuery()
            ->getResult();
    }

    public function getCommentsByUser($id){
        $qb = $this->createQueryBuilder('comments');

        $qb
            -> where('comments.userId = :id')
            -> setParameter('id', $id);

        return $qb
            ->getQuery()
            ->getResult();
    }
}
