# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/new, role: ROLE_ADMIN}
        - { path: ^/category, role: ROLE_ADMIN}
        - { path: ^/article, role: ROLE_ADMIN}

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: App\Entity\User
                property: username
        in_memory:
            memory:
                users:
                    user:  { password: pass, roles: [ 'ROLE_USER' ] }
                    admin: { password: pass, roles: [ 'ROLE_ADMIN' ] }
        fosuser_provider:
            id: fos_user.user_provider.username
    encoders:
        App\Entity\User:
          algorithm: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: bcrypt

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fosuser_provider
                csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    true

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
#    role_hierarchy:
#        # ROLE_ADMIN hérite du ROLE_USER
#        ROLE_ADMIN:       [ROLE_USER]